version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
    environment:
      - API_URL=http://localhost:5000/

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/data
    